"""
Unit tests for src/dashboard/data_loader.py (task 6.1).

Covers the pure color/parsing logic with synthetic data. The cached
GeoDataFrame/report loaders read real files generated by
prepare_dashboard_data.py and earlier tasks -- validated by a real run
(see developing.md's task 6.1 notes), not mocked.

Run with:
    pytest tests/test_dashboard_data_loader.py -v
"""
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from src.dashboard.data_loader import (  # noqa: E402
    build_style_function,
    flood_fill_color,
    parse_resolved_locations,
)


class TestFloodFillColor:
    def test_flooded_is_critical_red(self):
        assert flood_fill_color(1) == "#d03b3b"

    def test_dry_is_blue(self):
        assert flood_fill_color(0) == "#2a78d6"

    def test_accepts_numpy_like_ints(self):
        assert flood_fill_color(1.0) == "#d03b3b"  # int() coercion


class TestBuildStyleFunction:
    def test_colors_by_named_column(self):
        style_fn = build_style_function("gnn_pred")
        flooded_feature = {"properties": {"gnn_pred": 1, "baseline_pred": 0}}
        dry_feature = {"properties": {"gnn_pred": 0, "baseline_pred": 1}}
        assert style_fn(flooded_feature)["color"] == "#d03b3b"
        assert style_fn(dry_feature)["color"] == "#2a78d6"

    def test_missing_column_defaults_to_dry(self):
        style_fn = build_style_function("gnn_pred")
        assert style_fn({"properties": {}})["color"] == "#2a78d6"


class TestParseResolvedLocations:
    def test_parses_valid_json_list(self):
        raw = '[{"place": "Velachery", "lon": 80.22, "lat": 12.98, "score": 100.0}]'
        result = parse_resolved_locations(raw)
        assert result == [{"place": "Velachery", "lon": 80.22, "lat": 12.98, "score": 100.0}]

    def test_empty_string_gives_empty_list(self):
        assert parse_resolved_locations("") == []

    def test_none_gives_empty_list(self):
        assert parse_resolved_locations(None) == []

    def test_invalid_json_gives_empty_list_not_crash(self):
        assert parse_resolved_locations("not json") == []

    def test_empty_list_json_gives_empty_list(self):
        assert parse_resolved_locations("[]") == []
